#!/bin/bash

# Download and verify zlib
EXPECTEDCHECKSUM=76af0bfb4d17fad1d8bda13cb5593c311f59adee
curl -O http://zlib.net/zlib-1.2.10.tar.gz
CHECKSUM=$(shasum zlib-1.2.10.tar.gz | cut -b-40)
if [ "$EXPECTEDCHECKSUM" != "$CHECKSUM" ]; then
    echo "Zlib checksum verification failure"
    exit 1
fi;

# Unpack and compile zlib
tar -xzvf zlib-1.2.10.tar.gz
cd zlib-1.2.10
./configure
make

# Compile
cd ..
make plink
