#!/bin/bash
tar -xzvf zlib-1.2.7.tar.gz
cd zlib-1.2.7
./configure
make
cd ..
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then
  sudo yum install -y blas-devel lapack lapack-devel atlas-devel
fi
make wdist
