CSRC = SFMT.c hfile.c bgzf.c

ZCSRC = zstd/zlibWrapper/zstd_zlibwrapper.c zstd/zlibWrapper/gzclose.c zstd/zlibWrapper/gzlib.c zstd/zlibWrapper/gzread.c zstd/zlibWrapper/gzwrite.c zstd/lib/common/entropy_common.c zstd/lib/common/zstd_common.c zstd/lib/common/error_private.c zstd/lib/common/xxhash.c zstd/lib/common/fse_decompress.c zstd/lib/common/pool.c zstd/lib/common/threading.c zstd/lib/compress/fse_compress.c zstd/lib/compress/huf_compress.c zstd/lib/compress/zstd_double_fast.c zstd/lib/compress/zstd_fast.c zstd/lib/compress/zstd_lazy.c zstd/lib/compress/zstd_ldm.c zstd/lib/compress/zstd_opt.c zstd/lib/compress/zstd_compress.c zstd/lib/compress/zstdmt_compress.c zstd/lib/decompress/huf_decompress.c zstd/lib/decompress/zstd_decompress.c

CCSRC = plink2_base.cc pgenlib_internal.cc plink2.cc plink2_adjust.cc plink2_cmdline.cc plink2_common.cc plink2_compress_stream.cc plink2_data.cc plink2_decompress.cc plink2_export.cc plink2_filter.cc plink2_glm.cc plink2_help.cc plink2_import.cc plink2_ld.cc plink2_matrix.cc plink2_matrix_calc.cc plink2_misc.cc plink2_psam.cc plink2_pvar.cc plink2_random.cc plink2_set.cc plink2_stats.cc

OBJ = $(CSRC:.c=.o) $(ZCSRC:.c=.o) $(CCSRC:.cc=.o)

CSRC2 = $(foreach fname,$(CSRC),../$(fname))
ZCSRC2 = $(foreach fname,$(ZCSRC),../$(fname))
CCSRC2 = $(foreach fname,$(CCSRC),../$(fname))
OBJ2 = $(notdir $(OBJ))

OBJ3 = $(CSRC2:.c=.o) $(ZCSRC2:.c=.o) $(CCSRC2:.cc=.o)


ZSTD_INCLUDE = -Izstd/lib -Izstd/lib/common -Izstd/zlibWrapper
ZSTD_INCLUDE2 = -I../zstd/lib -I../zstd/lib/common -I../zstd/zlibWrapper

CLEAN = *.o zstd/lib/common/*.o zstd/lib/compress/*.o zstd/lib/decompress/*.o zstd/zlibWrapper/*.o build/plink2 build/pgen_compress
CLEAN3 = $(foreach expr,$(CLEAN),../$(expr))
