# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NewReader <- function(filename, raw_sample_ct = NULL, variant_ct = NULL, pvar = NULL, sample_subset = NULL) {
    .Call(`_pgenlibr_NewReader`, filename, raw_sample_ct, variant_ct, pvar, sample_subset)
}

GetRawSampleCt <- function(pgen) {
    .Call(`_pgenlibr_GetRawSampleCt`, pgen)
}

GetVariantCt <- function(pgen) {
    .Call(`_pgenlibr_GetVariantCt`, pgen)
}

HardcallPhasePresent <- function(pgen) {
    .Call(`_pgenlibr_HardcallPhasePresent`, pgen)
}

IntBuf <- function(pgen) {
    .Call(`_pgenlibr_IntBuf`, pgen)
}

Buf <- function(pgen) {
    .Call(`_pgenlibr_Buf`, pgen)
}

ReadHardcalls <- function(pgen, buf, variant_num, allele_num = 2L) {
    invisible(.Call(`_pgenlibr_ReadHardcalls`, pgen, buf, variant_num, allele_num))
}

Read <- function(pgen, buf, variant_num, allele_num = 2L) {
    invisible(.Call(`_pgenlibr_Read`, pgen, buf, variant_num, allele_num))
}

Close <- function(pgen) {
    invisible(.Call(`_pgenlibr_Close`, pgen))
}

NewPvar <- function(filename) {
    .Call(`_pgenlibr_NewPvar`, filename)
}

GetPvarCt <- function(pvar) {
    .Call(`_pgenlibr_GetPvarCt`, pvar)
}

GetVariantId <- function(pvar, variant_num) {
    .Call(`_pgenlibr_GetVariantId`, pvar, variant_num)
}

GetAlleleCt <- function(pvar, variant_num) {
    .Call(`_pgenlibr_GetAlleleCt`, pvar, variant_num)
}

GetAlleleCode <- function(pvar, variant_num, allele_num) {
    .Call(`_pgenlibr_GetAlleleCode`, pvar, variant_num, allele_num)
}

GetMaxAlleleCt <- function(pvar) {
    .Call(`_pgenlibr_GetMaxAlleleCt`, pvar)
}

ClosePvar <- function(pvar) {
    invisible(.Call(`_pgenlibr_ClosePvar`, pvar))
}

