#!/bin/sh
# Builds an S3-enabled plink2 and packages it as a .deb or .rpm that depends
# on the distribution's own libcurl, so the package manager supplies it (with
# the right CA-bundle path) and nothing is bundled.
#
# Run from 2.0/ inside the oldest release of the target distribution family;
# the package then installs on that release and newer ones.
#
#   usage: packaging/build_linux_package.sh deb|rpm [outdir]
set -eu

format="$1"
outdir="$(pwd)/${2:-dist}"

version=$(sed -n 's/.*ver_str\[\] = "PLINK v\([^"]*\)".*/\1/p' plink2.cc)
[ -n "$version" ] || { echo "could not read the version from plink2.cc" >&2; exit 1; }
# '~' sorts before the final release in both dpkg and rpm; '-' is not allowed.
pkgver=$(printf '%s' "$version" | tr '-' '~')
maintainer="${PACKAGE_MAINTAINER:-plink-ng contributors <noreply@users.noreply.github.com>}"
summary="PLINK 2 with S3/HTTP input support"
description="Whole genome association analysis toolset, built with libcurl so that
input files can be read directly from s3:// and https:// URLs."

# EL/Fedora keep cblas.h and lapacke.h in subdirectories.
CPATH="/usr/include/openblas:/usr/include/lapacke${CPATH:+:$CPATH}"
export CPATH
(cd build_dynamic && make clean > /dev/null && make USE_S3=1 -j"$(nproc)" plink2)
./build_dynamic/plink2 --version

mkdir -p "$outdir"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

case "$format" in
deb)
  arch=$(dpkg --print-architecture)
  root="$work/debian/plink2-s3"
  install -Dm755 build_dynamic/plink2 "$root/usr/bin/plink2"
  install -Dm644 COPYING "$root/usr/share/doc/plink2-s3/copyright"
  # dpkg-shlibdeps derives versioned Depends from the binary's NEEDED entries;
  # it only needs a stub debian/control to run.  Its libcurl4 floor comes from
  # symbol history, so it is raised to what CURLOPT_AWS_SIGV4 needs.
  printf 'Source: plink2-s3\n\nPackage: plink2-s3\nArchitecture: any\n' > "$work/debian/control"
  shlibs=$(cd "$work" && dpkg-shlibdeps -O debian/plink2-s3/usr/bin/plink2 2>/dev/null |
           sed -n 's/^shlibs:Depends=//p' |
           sed 's/libcurl4 ([^)]*)/libcurl4 (>= 7.75.0)/')
  case "$shlibs" in
    *libcurl4*) ;;
    *) echo "dpkg-shlibdeps did not report libcurl4: $shlibs" >&2; exit 1 ;;
  esac
  mkdir -p "$root/DEBIAN"
  cat > "$root/DEBIAN/control" <<EOF
Package: plink2-s3
Version: ${pkgver}-1
Architecture: ${arch}
Maintainer: ${maintainer}
Depends: ${shlibs}
Provides: plink2
Conflicts: plink2
Replaces: plink2
Section: science
Priority: optional
Homepage: https://www.cog-genomics.org/plink/2.0/
Description: ${summary}
$(printf '%s\n' "$description" | sed 's/^/ /')
EOF
  dpkg-deb --build --root-owner-group "$root" \
    "$outdir/plink2-s3_${pkgver}-1_${arch}.deb"
  ;;

rpm)
  mkdir -p "$work/SOURCES" "$work/SPECS"
  cp build_dynamic/plink2 COPYING "$work/SOURCES/"
  # Requires on libcurl.so.4, libopenblas etc. are generated by rpmbuild; only
  # the libcurl version floor has to be stated by hand.
  cat > "$work/SPECS/plink2-s3.spec" <<EOF
%global debug_package %{nil}
%global _build_id_links none

Name:      plink2-s3
Version:   ${pkgver}
Release:   1%{?dist}
Summary:   ${summary}
License:   GPL-3.0-or-later
URL:       https://www.cog-genomics.org/plink/2.0/
Requires:  libcurl >= 7.75.0
Provides:  plink2
Conflicts: plink2

%description
${description}

%build
cp %{_sourcedir}/COPYING .

%install
install -Dm755 %{_sourcedir}/plink2 %{buildroot}%{_bindir}/plink2

%files
%license COPYING
%{_bindir}/plink2
EOF
  rpmbuild --define "_topdir $work" -bb "$work/SPECS/plink2-s3.spec"
  find "$work/RPMS" -name '*.rpm' -exec cp {} "$outdir/" \;
  ;;

*)
  echo "usage: $0 deb|rpm [outdir]" >&2
  exit 2
  ;;
esac

ls -l "$outdir"
