# Builds Python wheels on many OSes, archs, and python versions with cibuildwheel

name: Build Python Wheels for Linux, Windows, Mac

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-14 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU for aarch64 emulation
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Setup python on macOS runner
      uses: actions/setup-python@v5
      if: runner.os == 'macOS'
      with:
        python-version: '3.12'

    - name: Install pipx on macOS runner
      if: runner.os == 'macOS'
      run: python -m pip install pipx

    - name: Create sdist and unpack into ./sdist/Pgenlib-latest
      working-directory: ./2.0/Python
      run: |
        pipx run build --sdist
        mkdir sdist
        tar -xf ./dist/pgenlib-*.tar.gz -C ./sdist
        mv ./sdist/* Pgenlib-latest/

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      with:
        package-dir: ./2.0/Python
      env:
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 universal2 arm64

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

    - name: Install from wheel
      run: |
        python -m pip install ./wheelhouse/*.whl
  
    - name: Test against newest numpy version
      working-directory: ./2.0/Python
      run: |
        python -m pip install numpy
        pytest tests/

    - name: Test against oldest supported numpy version
      working-directory: ./2.0/Python
      run: |
        python -m pip install numpy==1.19.0
        pytest tests/
