# Builds Python wheels on many OSes, archs, and python versions with cibuildwheel

name: Build Python Wheels for Linux, Windows, Mac

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for py3.${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: ["9", "10", "11", "12"]
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU for aarch64 emulation
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Setup python on macOS runner
      uses: actions/setup-python@v5
      if: startsWith(runner.os, 'macos')
      with:
        python-version: 3.${{ matrix.build }}

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      with:
        package-dir: ./2.0/Python
      env:
        CIBW_SKIP: "*-musllinux_*"
        CIBW_BUILD: "cp3${{ matrix.build }}-*"
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 universal2 arm64
        CIBW_ENVIRONMENT: "PIP_PRE=1" # we can remove this after 06/16/24 when numpy is officially published

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-3${{ matrix.build }}
        path: ./wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    env:
      job_python_version: "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.job_python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.job_python_version }}

      - name: Create source distribution
        working-directory: ./2.0/Python
        run: |
          pip install build
          python -m build --sdist .

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./2.0/Python/dist/pgenlib-*.tar.gz
