name: Build Python Wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-latest is apple silicon
        os: [ubuntu-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 emulation
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        with:
          package-dir: ./2.0/Python
        env:
          # skip building pypy for python 3.7 on macos-13 and both cpython and pypy for python 3.7 on macos-latest
          CIBW_SKIP: "{*-musllinux_*,pp37-macosx_x86_64,*p37-macosx_arm64}"
          CIBW_BUILD: "*p37-* *p38-* *p39-* *p310-* *p311-* *p312-*"
          CIBW_ARCHS_LINUX: x86_64 aarch64
          CIBW_ARCHS_MACOS: universal2
          # allow CIBW to find prerelease version of numpy. We can remove this after 06/16/24 when numpy is officially published
          # CIBW_ENVIRONMENT: PIP_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple PIP_PRE=1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {package}/tests"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  merge_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge wheel artifacts into a single artifact
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          pattern: wheels-*
          delete-merged: true

  build_sdist:
    runs-on: ubuntu-latest
    env:
      job_python_version: "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.job_python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.job_python_version }}

      - name: Create source distribution
        working-directory: ./2.0/Python
        run: |
          pip install build
          python -m build --sdist .

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./2.0/Python/dist/pgenlib-*.tar.gz
      
      - name: Install and test
        working-directory: ./2.0/Python
        run: |
          pip install --no-cache-dir --no-binary=pgenlib dist/pgenlib-*.tar.gz pytest
          pytest tests/
