name: PLINK2 DYNAMIC BUILD TESTS UBUNTU - AUTO

on:
  workflow_dispatch:   # manual trigger
  schedule:           # weekly trigger
    - cron: '0 0 * * 0'  # every Sunday at midnight

jobs:
  test_plink:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full commit history needed

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run Plink2 build/test script
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x 2.0/dynamic_build/CI-SCRIPTS/autocheckcommits_dynamicbuild_plink2tests_template.sh
          2.0/dynamic_build/CI-SCRIPTS/autocheckcommits_dynamicbuild_plink2tests_template.sh
