name: PLINK2 DYNAMIC BUILD TESTS UBUNTU - AUTO

on:
  workflow_dispatch:   # manual trigger
  schedule:           # weekly trigger
    - cron: '0 0 * * 0'  # every Sunday at 00:00 UTC
#   push:
#     branches:
#       - master

jobs:
  test_plink:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full commit history needed

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Check for new commits since last successful run
        id: commit_check
        env:
          GH_TOKEN: ${{ github.token }}   # GitHub-provided token
        run: |
          LATEST_COMMIT=$(git rev-parse origin/master)
          echo "Latest commit on master: $LATEST_COMMIT"

          # Get last successful workflow SHA
          LAST_RUN_COMMIT=$(gh run list \
            --workflow="PLINK2 DYNAMIC BUILD TESTS UBUNTU - AUTO" \
            --branch master \
            --status success \
            --limit 1 \
            --json headSha \
            --jq '.[0].headSha')

          echo "Last successful workflow commit: $LAST_RUN_COMMIT"

          if [ "$LATEST_COMMIT" = "$LAST_RUN_COMMIT" ]; then
            echo "No new commits since last successful run. Exiting."
            exit 0
          fi

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install gdown

      - name: Install BLAS/LAPACK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libopenblas-dev \
            liblapack-dev \
            liblapacke-dev \
            zlib1g-dev \
            unzip

      - name: Build Plink2 from source
        run: |
          source venv/bin/activate
          cd 2.0/build_dynamic
          make clean
          make
          sudo cp plink2 /usr/local/bin/plink2

      - name: Download test data
        run: |
          source venv/bin/activate
          GDRIVE_FILE_ID="1duspKrxtYdf_dJe5jX4Y_GMkzmy6i8dj"
          echo "Downloading test data from Google Drive..."
          gdown "https://drive.google.com/uc?id=$GDRIVE_FILE_ID" -O test_data.zip
          unzip test_data.zip -d test_data
          mv test_data/yesmiss_testdata/* test_data/
          rm -rf test_data/yesmiss_testdata

      - name: Run tests with Plink2
        run: |
          source venv/bin/activate
          mkdir -p ./derivatives/
          plink2 --pfile test_data/1kgp3_50k_yesmiss_Av_nonintdose --genotyping-rate dosage --out ./derivatives/tmp

      - name: List all files
        run: |
          ls ./test_data/*
          ls ./derivatives/*
