# This is a basic workflow that is manually triggered

name: PLINK2 GLM TESTS

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      plink_url:
        # Friendly description for the Plink URL input
        description: 'URL to download the Plink executable'
        # Input is required for the workflow to run
        required: true
        # Type of input (URL for Plink executable)
        type: string

jobs:
  test_plink:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code (if needed for further steps)
      - name: Checkout Plink2 repository code
        uses: actions/checkout@v4

      # Install dependencies (necessary for downloading and testing Plink)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential

      # Download the Plink binary from the provided URL
      - name: Download Plink executable
        run: |
          echo "Downloading Plink from ${PLINK_URL}..."
          wget -O plink.zip ${{ inputs.plink_url }}
          unzip plink.zip -d plink_dir
          chmod +x plink_dir/plink
          mv plink_dir/plink /usr/local/bin/plink

      # Run tests using the downloaded Plink executable
      - name: Run tests with Plink
        run: |
          echo "Running tests with the downloaded Plink executable..."
          plink --version # or replace with your test command

      # Optional: Check the output of the tests (if applicable)
      - name: Check Plink output
        run: |
          # If your tests produce output files like .assoc, you can check them here
          if [ -f "plink_result.assoc" ]; then
            cat plink_result.assoc
          fi

