# This is a basic workflow that is manually triggered

name: PLINK2 GLM TESTS

on:
  workflow_dispatch:
    inputs:
      plink_version_date:
        description: 'Enter the Plink version date (e.g., 20250129)'
        required: true
        type: string

jobs:
  test_plink:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plink2 repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential python3 python3-pip
          python3 -m pip install --upgrade pip
          pip3 install gdown

      - name: Download Plink executable
        run: |
          PLINK_BASE_URL="https://s3.amazonaws.com/plink2-assets/alpha6"
          PLINK_VERSION="${{ inputs.plink_version_date }}"
          PLINK_URL="$PLINK_BASE_URL/plink2_linux_amd_avx2_${PLINK_VERSION}.zip"

          echo "Downloading Plink from: $PLINK_URL"
          wget -O plink.zip "$PLINK_URL"

          if [ $? -ne 0 ]; then
            echo "Error: Failed to download Plink. Check if the version exists."
            exit 1
          fi

          unzip plink.zip -d plink_dir
          chmod +x plink_dir/plink2
          mv plink_dir/plink2 /usr/local/bin/plink2

      - name: Download test data
        run: |
          GDRIVE_FILE_ID="1duspKrxtYdf_dJe5jX4Y_GMkzmy6i8dj"
          echo "Downloading test data from Google Drive..."
          gdown "https://drive.google.com/uc?id=$GDRIVE_FILE_ID" -O test_data.zip
          unzip test_data.zip -d test_data

      - name: Run tests with Plink
        run: |
          echo "Running tests with Plink2..."
          plink2 --pfile test_data/1kgp3_50k_yesmiss_Av_nonintdose --genotype-count dosage --out tmp

      - name: Check Plink output
        run: |
          if [ -f "tmp.genotype-count" ]; then
            cat tmp.genotype-count
          else
            echo "No output file generated."
            exit 1
          fi

